Add size prop
selsa-inube/inubekit-assisted pull request #3
Opened 2024-03-19 22:57 UTC by cmarin001

This pull request introduces a new size prop to a specific UI component within our application. Designed to offer developers and designers more flexibility in customizing component dimensions, this update aligns with our commitment to providing a versatile and adaptable user interface. The size prop allows for predefined size options, enhancing the component's scalability across various application contexts and improving the overall user experience by accommodating different design requirements.

2024-03-19 23:10 UTC, JanuarAsprilla approved these changes

2024-03-27 02:15 UTC, wfercanas requested changes

2024-03-27 02:15 UTC, wfercanas commented on src/Assisted/index.tsx
> +      width={size === "small" ? "312px" : "auto"}
This prop has typescript problems:

![image](https://github.com/selsa-inube/inubekit-assisted/assets/36939686/10c47dcc-8839-413a-9cbd-7d02a708527a)

2024-03-27 22:49 UTC, cmarin001 commented on src/Assisted/index.tsx
> +      width={size === "small" ? "312px" : "auto"}
solved

2024-04-01 15:11 UTC, wfercanas approved these changes

2024-04-01 15:13 UTC, merged