Refactor `<Assisted />` component to use new token structure
selsa-inube/inubekit-assisted pull request #6
Opened 2024-03-22 19:53 UTC by JanuarAsprilla

the structure of the `<Assisted />` component is updated to make it more usable and in accordance with the tokens and other components it needs.

2024-03-27 21:18 UTC, wfercanas requested changes

2024-03-27 21:18 UTC, wfercanas commented on src/Assisted/index.tsx
>    return (
Button appearance shouldn't be "primary" hardcoded, we must use tokens to set that appearance.

2024-03-27 21:18 UTC, wfercanas commented on src/Assisted/index.tsx
>    return (
Icon appearance shouldn't be hardcoded either

2024-03-27 21:18 UTC, wfercanas commented on src/Assisted/index.tsx
>    return (
Text appearance for title, descriptions, and step number shouldn't be hardcoded.

2024-03-27 21:18 UTC, wfercanas commented on src/Assisted/styles.js
> +    theme?.assisted?.step?.color || inube.assisted.step.color};
Instead of `step.color` we should use `bar.color`

2024-03-27 21:18 UTC, wfercanas commented on src/Assisted/styles.js
> +    theme?.assisted?.bar?.color || inube.assisted.bar.color};
Instead of `bar.color`, we should use `step.color`

2024-03-27 21:18 UTC, wfercanas commented on src/Assisted/styles.js
The background of the component is not aligned with the tokens. It shouldn't be fully white.

Storybook:
![image](https://github.com/selsa-inube/inubekit-assisted/assets/36939686/aa91999f-7c94-4783-a54b-8023a1418ba4)

Figma:
![image](https://github.com/selsa-inube/inubekit-assisted/assets/36939686/cfbab051-4b42-4a06-92c4-741d974d0b4e)

Excel:
![image](https://github.com/selsa-inube/inubekit-assisted/assets/36939686/f7cf3b77-3870-403c-9fde-cd329485cf7f)

2024-03-29 19:59 UTC, JanuarAsprilla commented on src/Assisted/styles.js
> +    theme?.assisted?.bar?.color || inube.assisted.bar.color};
solved

2024-03-29 20:16 UTC, JanuarAsprilla commented on src/Assisted/styles.js
> +    theme?.assisted?.step?.color || inube.assisted.step.color};
solved

2024-03-29 20:58 UTC, JanuarAsprilla commented on src/Assisted/styles.js
solved

2024-04-01 16:52 UTC, JanuarAsprilla commented on src/Assisted/index.tsx
>    return (
solved

2024-04-01 17:34 UTC, JanuarAsprilla commented on src/Assisted/index.tsx
>    return (
solved

2024-04-05 22:09 UTC, merged